# Generated by Django 5.2.2 on 2025-06-08 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recorrido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('punto_recogida', models.CharField(max_length=100)),
                ('punto_dejada', models.CharField(max_length=100)),
                ('distancia_recorrida', models.FloatField(default=0, help_text='Distancia estimada en kilómetros')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recorrido')),
            ],
        ),
    ]
