# Generated by Django 5.2.2 on 2025-06-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicituddeviaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='distancia_km',
            field=models.FloatField(blank=True, help_text='Distancia real entre origen y destino en km', null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='lat_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='lat_origen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='lon_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='lon_origen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddeviaje',
            name='lat_dejada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddeviaje',
            name='lat_recogida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddeviaje',
            name='lon_dejada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddeviaje',
            name='lon_recogida',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
