# Generated by Django 5.2.2 on 2025-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recorrido_distancia_km_recorrido_lat_destino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorrido',
            old_name='lat_destino',
            new_name='destino_lat',
        ),
        migrations.RenameField(
            model_name='recorrido',
            old_name='lat_origen',
            new_name='destino_lon',
        ),
        migrations.RenameField(
            model_name='recorrido',
            old_name='lon_destino',
            new_name='origen_lat',
        ),
        migrations.RenameField(
            model_name='recorrido',
            old_name='lon_origen',
            new_name='origen_lon',
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='destino',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='origen',
            field=models.CharField(max_length=255),
        ),
    ]
