# Generated by Django 5.2.2 on 2025-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_lat_destino_recorrido_destino_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='ubicacion_actual_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='ubicacion_actual_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
